################
# DEFAULT APPS #
################

$terminal = kitty
$fileManager = thunar
$taskmanager = kitty -e btop
$notifications = swaync-client -t -sw
$browser = zen-browser
$discord = discord
$screenshot = grim -g "$(slurp)" - | wl-copy
$rofi=~/.config/rofi
$menu = $rofi/launcher/launcher.sh
$powerMenu = $rofi/powermenu/powermenu.sh
$windowSwitcher = $rofi/windowswitcher/windowswitcher.sh
$clipboard = $rofi/clipboard/clipboard.sh
$bluetooth = $rofi/bluetooth/bluetooth.sh

################
# STARTUP APPS #
################

exec-once = systemctl --user start hyprpolkitagent
exec-once = waybar
exec-once = swaync
exec-once = hyprpaper
exec-once = openrgb -p catppuccin.orp
exec-once = hyprctl setcursor catppuccin-mocha-lavender-cursors 24
exec-once = wl-paste --type text --watch cliphist store

